var secretNumber, guessedNumber;
var oldGuesses = [];
var randomizer = function(){
	return Math.floor((Math.random() * 100) + 1);
};
var isHotter = function(oldNum, newNum, winNum){
	oldDif = Math.abs(winNum-oldNum);
	newDif = Math.abs(winNum-newNum);
	if(newDif < oldDif){
		return true;
	}else{
		return false;
	}
};
var newGame = function(){
	//hides play again button
	$(".playAgain").hide();
	$(".feedback").text("Welcome! Pick a number between 1 and 100");
};
$(document).ready(function(){
var resetAlerts = function(){
	$(".feedback").removeClass("alert-success");
	$(".feedback").removeClass("alert-warning");
	$(".feedback").removeClass("alert-info");
	$(".feedback").removeClass("alert-danger");
};
	newGame();

	//a random number is generated by the computer
	secretNumber = randomizer();
	//on click of guess button
	$(".guess").on("click", function(){
		//stores users guess
		guessedNumber = +$(".guessInput").val();
		
		//verifies that guessedNumber is a valid guess between 1-100
		if(isNaN(guessedNumber)){
			resetAlerts();
			$(".feedback").addClass("alert-warning");
			$(".feedback").text(":( That wasn't a valid number");
			$(".guessInput").val("");
		}
		if(guessedNumber < 0|| guessedNumber > 100){
			resetAlerts();
			$(".feedback").addClass("alert-warning");
			$(".feedback").text("That number wasn't between 1-100, try again!");
			$(".guessInput").val("");
		}
		//checks to see if guessedNumber is a winner
		if(guessedNumber===secretNumber){
			resetAlerts();
			$(".feedback").addClass("alert-success");
			$(".feedback").text("You won! And it only took you "+oldGuesses.length+" tries!");
			$(".guessInput").val("");
			//shows play again button
			$(".playAgain").show();
		}
		//if guessedNumber isn't a winner:
		else{
			//keeps track of the guessedNumber
			oldGuesses.push(guessedNumber);
			//if this is the first guess, prompt to try again
			if(oldGuesses.length < 2){
				resetAlerts();
				$(".feedback").addClass("alert-warning");
				$(".feedback").text("A good first guess, but try again");
				$(".guessInput").val("");
			}
			//checks to see if hotter or colder
			else if(isHotter(oldGuesses[oldGuesses.length-2],oldGuesses[oldGuesses.length-1],secretNumber)){
				resetAlerts();
				$(".feedback").addClass("alert-danger");
				$(".feedback").text("****Getting Warmer****");
				$(".guessInput").val("");
			}
			else{
				resetAlerts();
				$(".feedback").addClass("alert-info");
				$(".feedback").text("Brrrr.... you're colder");
				$(".guessInput").val("");
			}
		}
	});
});
